runtime: python37

handlers:
- url: /.*
  script: auto

- url: /static
  static_dir: static

automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_concurrent_requests: 2

env_variables:
  PROJECT_ID: '[Your Project ID]'
  DEBUG: False

includes:
- secret.yaml
